name: deploy-container

on:
  push:
    branches:
      - main
    paths: 
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      — name: checks out code
        uses: actions/checkout@v2
      — name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ‘16.x’
          registry-url: https://registry.npmjs.org
      — name: Install dependencies using a safe clean install
        run: npm ci — ignore-scripts
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      - uses: actions/checkout@v3
      - run: npm install --registry https://registry.npmjs.org
      - run: npm run build



